
package ca.bcit.comp4656.jaxws.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BasicEmployeeServiceService", targetNamespace = "http://services.jaxws.comp4656.bcit.ca/", wsdlLocation = "http://localhost:8080/A00871798ws/BasicEmployeeService?wsdl")
public class BasicEmployeeServiceService
    extends Service
{

    private final static URL BASICEMPLOYEESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BASICEMPLOYEESERVICESERVICE_EXCEPTION;
    private final static QName BASICEMPLOYEESERVICESERVICE_QNAME = new QName("http://services.jaxws.comp4656.bcit.ca/", "BasicEmployeeServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/A00871798ws/BasicEmployeeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BASICEMPLOYEESERVICESERVICE_WSDL_LOCATION = url;
        BASICEMPLOYEESERVICESERVICE_EXCEPTION = e;
    }

    public BasicEmployeeServiceService() {
        super(__getWsdlLocation(), BASICEMPLOYEESERVICESERVICE_QNAME);
    }

    public BasicEmployeeServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BASICEMPLOYEESERVICESERVICE_QNAME, features);
    }

    public BasicEmployeeServiceService(URL wsdlLocation) {
        super(wsdlLocation, BASICEMPLOYEESERVICESERVICE_QNAME);
    }

    public BasicEmployeeServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BASICEMPLOYEESERVICESERVICE_QNAME, features);
    }

    public BasicEmployeeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicEmployeeServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeServicePort
     */
    @WebEndpoint(name = "BasicEmployeeServicePort")
    public EmployeeServicePort getBasicEmployeeServicePort() {
        return super.getPort(new QName("http://services.jaxws.comp4656.bcit.ca/", "BasicEmployeeServicePort"), EmployeeServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeServicePort
     */
    @WebEndpoint(name = "BasicEmployeeServicePort")
    public EmployeeServicePort getBasicEmployeeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.jaxws.comp4656.bcit.ca/", "BasicEmployeeServicePort"), EmployeeServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BASICEMPLOYEESERVICESERVICE_EXCEPTION!= null) {
            throw BASICEMPLOYEESERVICESERVICE_EXCEPTION;
        }
        return BASICEMPLOYEESERVICESERVICE_WSDL_LOCATION;
    }

}
